# Generated by Django 5.2.7 on 2025-10-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('setting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('theme_preference', models.TextField(default='light')),
                ('notification_preference', models.TextField(default='all')),
                ('language', models.TextField(default='en')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profile_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('search_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('search_term', models.TextField()),
                ('search_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_history',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='passwordrecovery',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='postvote',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='ProfileSetting',
        ),
    ]
