# Generated by Django 5.2.7 on 2025-10-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profilesettings_searchhistory_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='passwordrecovery',
            table='password_recovery',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='postvote',
            table='post_votes',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='resources',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
