# Generated by Django 5.2.7 on 2025-12-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_category_table_alter_comment_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken')], default='pending')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken')], default='pending')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('violation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('display_name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('severity_level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'violation_types',
                'managed': False,
            },
        ),
    ]
